Hidden refac
Adalab/easly-s2-.forEach-Adalabers- pull request #2
Opened 2019-01-05 11:17 UTC by aroatdlt

Hi girls,

I have tried to write less code in this file and fix the problem with the arrows...(when you click in other section, the last arrow clicked dont change his class (cry)). But maybe some of you have another idea about why it is happening...
I'm sure that it is a silly thing but I dont find it...je je.
Thanks team!!!!!!!!!

2019-01-05 11:32 UTC, aroatdlt commented
@claraharguindey @alteapin @lauraferrandof @minamrp

2019-01-05 19:33 UTC, lauraferrandof commented
@aroatdlt I think I know the problem!! I'll comment the concrete lines in the "files changed" section.
But awesome job on those reusable functions!!!!!!!! It's great!!

2019-01-05 19:39 UTC, lauraferrandof commented
@aroatdlt I think it works with those 2 small changes I indicated... if it doesn't, let us know so we can check it out once more!

2019-01-05 20:10 UTC, claraharguindey commented
@lauraferrandof in what line is your comment? I'm curious but I can not find it!

2019-01-05 20:44 UTC, lauraferrandof commented
@claraharguindey I didn't change the code in our files, I just commented the lines here in GitHub. You can see it just above your comment!

2019-01-06 18:30 UTC, claraharguindey commented
@lauraferrandof yeah I know, but I don't see the lines! maybe that comments are only available for Aroa(?) hahha stranger things... /cosas raritas/.

2019-01-06 19:43 UTC, sayheylaura requested changes
@aroatdlt @claraharguindey let me know if you can see my comments now!

2019-01-06 19:43 UTC, sayheylaura commented on _src/assets/js/partials/hidden.js
> +  if (firstArrowElement.classList.contains('.fa-chevron-up')) {
just delete line 24. you can leave the 2 next lines (25 and 26) right after line 23. also don't forget to delete the `}` symbol in line 27

2019-01-06 19:43 UTC, sayheylaura commented on _src/assets/js/partials/hidden.js
> +  if (secondArrowElement.classList.contains('.fa-chevron-up')) {
same here! delete line 32, leave lines 33 and 34, and delete the `}` symbol in line 35

2019-01-06 19:43 UTC, sayheylaura commented on _src/assets/js/partials/hidden.js
> +  if (currentClicked === buttonFillElement) {
also, consider writing an `else if` instead of `if` alone. same in line 50, although here it should work with a final `else` alone

2019-01-08 18:56 UTC, sayheylaura approved these changes

2019-01-08 18:58 UTC, merged